name: Tech Blog Post Feed Data
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  finalized-blogs:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://qubitpi.github.io/jersey-guide/feed/FINALIZED.xml"
  MGMT-blogs:
    name: Update this repos README with MGMT blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MGMT-BLOG-POST-LIST"
          max_post_count: "5"
          feed_list: "https://qubitpi.github.io/jersey-guide/feed/MANAGEMENT.xml"
  WIP-blogs:
    name: Update this repos README with WIP blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "WIP-BLOG-POST-LIST"
          max_post_count: "6"
          feed_list: "https://qubitpi.github.io/jersey-guide/feed/WIP.xml"
