name: Tech News
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  google-ai-blogs:
    name: Google AI Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Google AI Blog"
          comment_tag_name: "GOOGLE-AI-BLOG"
          max_post_count: "5"
          feed_list: "http://feeds.feedburner.com/blogspot/gJZg"
  google-deepmind-blogs:
    name: Google DeepMind Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Google DeepMind Blog"
          comment_tag_name: "GOOGLE-DEEPMIND-BLOG"
          max_post_count: "5"
          feed_list: "https://www.deepmind.com/blog/rss.xml"          

  hashicorp-blogs:
    name: HashiCorp Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New HashiCorp Blog"
          comment_tag_name: "HASHICORP-BLOG"
          max_post_count: "5"
          feed_list: "https://www.hashicorp.com/blog/feed.xml"    

  neo4j-youtube:
    name: Neo4j - YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Neo4J Videos"
          comment_tag_name: "NEO4J-YOUTUBE"
          max_post_count: "5"
          feed_list: "https://rsshub.app/youtube/channel/UCvze3hU6OZBkB1vkhH2lH9Q"

  openstack-news:
    name: OpenStack News
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "OpenStack Superuser"
          comment_tag_name: "OPENSTACK-SUPERUSER"
          max_post_count: "5"
          feed_list: "https://superuser.openstack.org/feed/"
   
  martin-fowler-blog:
    name: Martin Fowler's Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "Martin Fowler's New Blog"
          comment_tag_name: "MARTIN-FOWLER-BLOG"
          max_post_count: "5"
          feed_list: "https://martinfowler.com/feed.atom"
