name: Tech News
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  google-ai-blogs:
    name: Google AI Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Google AI Blog"
          comment_tag_name: "GOOGLE-AI-BLOG"
          max_post_count: "5"
          feed_list: "http://feeds.feedburner.com/blogspot/gJZg"
  google-deepmind-blogs:
    name: Google DeepMind Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Google DeepMind Blog"
          comment_tag_name: "GOOGLE-DEEPMIND-BLOG"
          max_post_count: "5"
          feed_list: "https://www.deepmind.com/blog/rss.xml"          
  reddit-ml:
    name: ML Reddit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "ML Reddit"
          comment_tag_name: "REDDIT-ML"
          max_post_count: "5"
          feed_list: "https://www.reddit.com/r/MachineLearning/.rss"  
 
   scholia-entity-linking:
    name: [Scholia] Entity Linking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "Recently published works on Entity Linking"
          comment_tag_name: "SCHOLIA-ENTITY-LINKING"
          max_post_count: "5"
          feed_list: "https://scholia.toolforge.org/topic/Q17012245/latest-works/rss"
          template: "[$date] [$title]($url)"

  openstack-superuser:
    name: OpenStack Superuser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "OpenStack Superuser"
          comment_tag_name: "OPENSTACK-SUPERUSER"
          max_post_count: "5"
          feed_list: "https://superuser.openstack.org/feed/"

  memgraph-twitter:
    name: Twitter @Memgraph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Memgraph Twitter Posts"
          comment_tag_name: "MEMGRAPH-TWITTER"
          max_post_count: "5"
          feed_list: "https://rsshub.app/twitter/user/memgraphdb"
  neo4j-twitter:
    name: Twitter @Neo4j
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Neo4J Twitter Posts"
          comment_tag_name: "NEO4J-TWITTER"
          max_post_count: "5"
          feed_list: "https://rsshub.app/twitter/user/neo4j"
  neo4j-youtube:
    name: Neo4j - YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Neo4J Videos"
          comment_tag_name: "NEO4J-YOUTUBE"
          max_post_count: "5"
          feed_list: "https://rsshub.app/youtube/channel/UCvze3hU6OZBkB1vkhH2lH9Q"
   
  martin-fowler-blog:
    name: Martin Fowler's Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "Martin Fowler's New Blog"
          comment_tag_name: "MARTIN-FOWLER-BLOG"
          max_post_count: "5"
          feed_list: "https://martinfowler.com/feed.atom"

  css-tricks:
    name: CSS Tricks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New CSS Tricks"
          comment_tag_name: "CSS-TRIKCS"
          max_post_count: "5"
          feed_list: "https://css-tricks.com/feed/"
