name: News Central Feed
on:
  schedule:
    # Runs every hour
    - cron: '20 * * * *'
  workflow_dispatch:

jobs:
  arangodb-blogs:
    name: ArangoDB Blogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New ArangoDB Blogs"
          comment_tag_name: "ARANGO-BLOGS"
          max_post_count: "5"
          feed_list: "https://rss.app/feeds/q4XkB1Z7kdXRBkgM.xml"
  arangodb-twitter:
    name: Arango Twitter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New ArangoDB Twitter Posts"
          comment_tag_name: "ARANGO-TWITTER"
          max_post_count: "5"
          feed_list: "https://rsshub.app/twitter/user/arangodb"
  memgraph-twitter:
    name: Memgraph Twitter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Memgraph Twitter Posts"
          comment_tag_name: "MEMGRAPH-TWITTER"
          max_post_count: "5"
          feed_list: "https://rsshub.app/twitter/user/memgraphdb"
  neo4j-twitter:
    name: Neo4J Twitter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Neo4J Twitter Posts"
          comment_tag_name: "NEO4J-TWITTER"
          max_post_count: "5"
          feed_list: "https://rsshub.app/twitter/user/neo4j"
  neo4j-youtube:
    name: Neo4J YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Neo4J Videos"
          comment_tag_name: "NEO4J-YOUTUBE"
          max_post_count: "5"
          feed_list: "https://rsshub.app/youtube/channel/UCvze3hU6OZBkB1vkhH2lH9Q"
  janusgraph-twitter:
    name: JanusGraph Twitter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New JanuesGraph Twitter Posts"
          comment_tag_name: "JANUSGRAPH-TWITTER"
          max_post_count: "5"
          feed_list: "https://rsshub.app/twitter/user/JanusGraph"
          
  graphql-twitter:
    name: GraphQL Twitter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New GraphQL Twitter Posts"
          comment_tag_name: "GRAPHQL-TWITTER"
          max_post_count: "5"
          feed_list: "https://rsshub.app/twitter/user/graphql"
  graphql-spec-significant-changes:
    name: GraphQL Spec Significant Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New GraphQL Spec Changes"
          comment_tag_name: "GRAPHQL-SPEC-SIGNIFICANT-CHANGES"
          max_post_count: "5"
          feed_list: "https://rsshub.app/github/file/graphql/graphql-spec/main/spec"
          template: "<li>$date <a href=$url>$title</a></li>"                    
  graphql-java-significant-changes-antlr:
    name: GraphQL Java Significant Changes (ANTLR Grammar)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New GraphQL Java ANTLR Changes"
          comment_tag_name: "GRAPHQL-JAVA-SIGNIFICANT-CHANGES-ANTLR"
          max_post_count: "5"
          feed_list: "https://rsshub.app/github/file/graphql-java/graphql-java/master/src/main/antlr"
          template: "<li>$date <a href=$url>$title</a></li>"
       
  openstack-twitter:
    name: OpenStack Twitter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New GraphQL Twitter Posts"
          comment_tag_name: "OPENSTACK-TWITTER"
          max_post_count: "5"
          feed_list: "https://rsshub.app/twitter/user/OpenStack" 
  dockerhub-blog:
    name: DockerHub Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New DockerHub Blog"
          comment_tag_name: "DOCKERHUB-BLOG"
          max_post_count: "5"
          feed_list: "https://www.docker.com/feed/"
  kubernetes-blog:
    name: Kubernetes Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Kubernetes Blog"
          comment_tag_name: "KUBERNETES-BLOG"
          max_post_count: "5"
          feed_list: "https://kubernetes.io/feed.xml"
  kubernetes-doc-changes:
    name: Kubernetes Doc Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "Kubernetes doc changes"
          comment_tag_name: "KUBERNETES-DOC-CHANGES"
          max_post_count: "5"
          feed_list: "https://rsshub.app/github/pull/kubernetes/website/closed"
          template: "<li>$date <a href=$url>$title</a></li>"
  helm-doc-changes:
    name: Helm Doc Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "Helm doc changes"
          comment_tag_name: "HELM-DOC-CHANGES"
          max_post_count: "5"
          feed_list: "https://rsshub.app/github/file/helm/helm-www/main/content/en"
          template: "<li>$date <a href=$url>$title</a></li>"
     
  lets-encrypt-blog:
    name: Let's Encrypt Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New LetsEncrypt Blog"
          comment_tag_name: "LETS-ENCRYPT-BLOG"
          max_post_count: "5"
          feed_list: "https://letsencrypt.org/feed.xml"          

  web3-foundation-twitter:
    name: Web3 Foundation Twitter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Web3 Foundation Blog"
          comment_tag_name: "WEB3-FOUNDATION-TWITTER"
          max_post_count: "5"
          feed_list: "https://rsshub.app/twitter/user/web3foundation"
          
  dribbble:
    name: Dribbble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "QubitPi"
          committer_email: "jack20191124@proton.me"
          commit_message: "New Dribbble Trending"
          comment_tag_name: "DRIBBBLE-TRENDING"
          max_post_count: "5"
          feed_list: "https://rsshub.app/dribbble/popular/week"
